spring:
  application:
    name: elasticsearch


  elasticsearch:
    jest:
      uris: http://192.168.174.131:9200/
      read-timeout: 5000
      connection-timeout: 5000
      username: elastic
      password: elastic

server:
  port: 2001