spring:
  application:
    name: service-turbine

server:
  port: 1901

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: "*"
        allowed-origins: "*"

turbine:
  app-config: service-ribbon,ribbon-turbine
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream